site_name: homelab-handbook
nav:
  - Accueil: index.md
  - Knowledge Base:
    - Méthode: knowledge-base.md
    - Stack recommandée: stack-recommandee.md
  - Homelab:
    - Réseau: homelab/network.md
    - Proxmox: proxmox.md
  - Home Assistant:
    - Vue générale: home-assistant.md
    - Chauffage Frisquet: home-assistant/chauffage-frisquet.md
  - IA:
    - Frigate: ia/frigate.md
  - Incidents:
    - Journal: incidents/incidents.md